version: '3.8'

services:
  algorithm-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8080
    networks:
      - algorithm-network

networks:
  algorithm-network:
    driver: bridge